name: app_package_publisher
description: App package publisher
version: 0.3.0
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pubspec_parse: ^1.1.0
  shell_executor: ^0.1.1
dev_dependencies:
  dependency_validator: ^3.0.0
