name: flutter_app_publisher
description: Flutter app publisher
version: 0.3.0
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_publisher: ^0.3.0
  dio: ^4.0.4
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  parse_app_package: ^0.2.5+1
  qiniu_sdk_base: ^0.3.2
  shell_executor: ^0.1.1
dev_dependencies:
  dependency_validator: ^3.0.0
